using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DRObjects.Graphics
{
    /// <summary>
    /// Enum referring to global Sprites
    /// </summary>
    public enum GlobalSpriteName
    {
        RIVER,
        DESERTTILE,
        SWAMPTILE,
        SNOWTILE,
        GARIGUETILE,
        FORESTTILE,
        WATERTILE,
        GRASSTILE,
        BIGTREE,
        TREE,
        TROPICALTREE,
        DEADTREE,
        HILLSLOPE,
        MOUNTAIN,

        HAMLET,
        CAPITAL,
        VILLAGE,
        CAPITAL_1,
        CAPITAL_2,
        CAPITAL_3,
        CAPITAL_4,
        CAPITAL_5,
        CAPITAL_6,
        CAPITAL_7,
        CAPITAL_8,
        CAPITAL_9,
        HAMLET_1,
        HAMLET_2,
        HAMLET_3,
        HAMLET_4,
        HAMLET_5,
        HAMLET_6,
        HAMLET_7,
        HAMLET_8,
        HAMLET_9,
        VILLAGE_1,
        VILLAGE_2,
        VILLAGE_3,
        VILLAGE_4,
        VILLAGE_5,
        VILLAGE_6,
        VILLAGE_7,
        VILLAGE_8,
        VILLAGE_9,
        HORSES,
        GAME,
        FARMLAND,
        STONES,
        DUNGEON,
        DUNGEON_1,
        DUNGEON_2,
        DUNGEON_3,
        DUNGEON_4,
        DUNGEON_5,
        DUNGEON_6,
        DUNGEON_7,
        DUNGEON_8,
        DUNGEON_9,
        BANDIT_CAMP,
        DOVE,
        IRON_MINE,
        GOLD_MINE,
        FARM,
        FISHING_HUT,
        WOODCUTTER,
        HUNTER,
        STABLES,
    }
}
