using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace DRObjects.Graphics
{
    public enum LocalSpriteName
    {
        //Tiles
        WOOD_TILE,
        SAND_TILE,
        WET_SAND_TILE,
        DARK_TILE,
        LAVA_TILE,
        ROUGH_STONE_TILE,
        COBBLESTONE_TILE,
        SWAMP_TILE,
        DIRT_TILE,
        SOIL_TILE,
        DUNGEON_1_TILE,
        DUNGEON_2_TILE,
        DUNGEON_3_TILE,
        SKULL_TILE,
        DUNGEON_4_TILE,
        SAVANNAH_TILE,
        WOOD_2_TILE,
        ROAD_TILE,
        RUIN_TILE,
        DUNGEON_5_TILE,
        DUNGEON_6_TILE,
        DUNGEON_7_TILE,
        DUNGEON_8_TILE,
        DUNGEON_9_TILE,
        DUNGEON_10_TILE,
        GRASS_TILE,
        //Town Indoor Items
        BLUE_BED,
        WOOD_CHAIR_LEFT,
        WOOD_CHAIR_RIGHT,
        WOOD_CHAIR_BOTTOM,
        WOOD_CHAIR_TOP,
        EMPTY_SHELFING,
        BOOKCASE_FULL,
        BOOKCASE_HALF_EMPTY,
        GLASSWARE_CABINET,
        SMALL_RUG,
        CHEST_OF_DRAWERS,
        CHEST_OF_DRAWERS_1,
        CHEST_OF_DRAWERS_2,
        CHEST_OF_DRAWERS_3,
        CHEST_OF_DRAWERS_4,
        CABINET_1,
        WARDROBE_1,
        WARDROBE_2,
        WARDROBE_3,
        WARDROBE_4,
        STOVE_UNLIT,
        STOVE_LIT,
        PUMP,
        DISHES,
        TABLE_1,
        DOOR_CLOSED,
        DOOR_OPEN,
        FOUNTAIN_SMALL,
        STATUE_AXEMAN,
        WHITE_BED,
        PLANT_POT_1,
        PLANT_POT_2,
        TABLE_2,
        BEARSKIN_RUG,
        BOOKCASE_LARGE,
        BLUE_WALL,
        POTS,
        RED_BED_DOUBLE,
        RED_BED,
        TABLE_3,
        TABLE_4,
        LAMP_1,
        LAMP_2,
        PLANT_POT_3,
        NICE_CHAIR_RIGHT,
        NICE_CHAIR_LEFT,
        NICE_CHAIR_TOP,
        NICE_CHAIR_BOTTOM,
        BLUE_POT_LARGE,
        BARSTOOL,
        BLUE_POT_SMALL,
        DARK_RED_WALL,
        LIGHT_RED_WALL,
        BARREL,
        BARRELS,
        CHEST_CLOSED,
        CHEST_OPEN,
        PLAYERCHAR,

        BOOKCASE_1,
        BOOKCASE_2,
        BOOKCASE_3,
        BOOKCASE_4,

        DESK_1,
        DESK_2,
        DESK_3,

        PLANT_CABINET_1,
        PLANT_CABINET_2,
        PLANT_CABINET_3,

        WINDOW_1,
        WINDOW_2,
        WINDOW_3,

        DOOR_1_OPEN,
        DOOR_1_CLOSED,
        DOOR_2_OPEN,
        DOOR_2_CLOSED,

        POT_PLANT_1,
        POT_PLANT_2,
        POT_PLANT_3,
        POT_PLANT_4,

        BATH,

        CARPET_1,
        CARPET_2,
        CARPET_3,

        RED_BED_TOP,
        RED_BED_BOTTOM,

        BUCKET,

        BAR,

        //Resources
        WOOD_LOGS,
        WOOD_LOGS_THREE,
        FLOUR_SACK,
        FLOUR_SACK_THREE,
        GRAIN_OPEN,
        GRAIN_OPEN_THREE,
        GREEN_OPEN,
        GREEN_OPEN_THREE,
        STEAK,
        STEAK_THREE,
        DRUMSTICKS,
        DRUMSTICKS_THREE,
        CHICKEN,
        CHICKEN_THREE,
        MEAT,
        MEAT_THREE,
        ANVIL,
        ANVIL_2,
        SMITH_TOOLS_1,
        SMITH_TOOLS_2,
        SMITH_TOOLS_3,
        EMPTY_STALL,
        VEG_1,
        VEG_STALL_1,
        VEG_2,
        VEG_STALL_2,
        VEG_3,
        VEG_STALL_3,
        VEG_4,
        VEG_STALL_4,
        VEG_5,
        VEG_STALL_5,
        VEG_6,
        VEG_STALL_6,
        VEG_7,
        VEG_STALL_7,
        FISH_1,
        FISH_2,
        FISH_3,
        FISH_4,
        GOLD_BARS_1,
        GOLD_BARS_2,
        BREAD_THREE,
        BREAD_TWO,
        FLOUR_MILL,
        BOXES,
        TREE_STUMPS,
        PICKAXE,
        HATCHET_SHOVEL,
        MILK_JUGS,
        OIL_JARS,
        GOLD_ORE,
        IRON_ORE,
        COPPER_ORE,
        MINING_TOOLS,
        FURNACE,
        IRON_BARS_1,
        IRON_BARS_2,

        ANGEL_STATUE_TOP,
        ANGEL_STATUE_BOTTOM,

        FLOWER_1,
        FLOWER_2,
        FLOWER_3,
        FLOWER_4,
        FLOWER_5,
        FLOWER_6,
        FLOWER_7,
        FLOWER_8,
        FLOWER_9,
        FLOWER_10,
        FLOWER_11,
        FLOWER_12,
        FLOWER_13,
        FLOWER_14,
        FLOWER_15,
        FLOWER_16,
        FLOWER_17,

        TOMATO_PLANT,
        POTATO_PLANT,
        CARROT_PLANT,
        ARTICHOKE_PLANT,
        PEPPER_PLANT,
        COURGETTE_PLANT,
        CORN_PLANT,
        TOMATO,
        POTATO,
        CARROT,
        ARTICHOKE,
        PEPPERS,
        COURGETTE,
        CORN,

        //Forests and Mines and stuff
        TREE_1,
        TREE_2,
        TREE_3,
        DEAD_TREE
        

    }
}
